server:
  servlet-path: /koala/synthe
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.127.212:3306/micro_koala_synthe_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mikouo
    password: mikouo123
    initialize: false
    tomcat:
      max-active: 200
      test-while-idle: false
      test-on-borrow: true
      validation-query: select 1
      remove-abandoned: true
      remove-abandoned-timeout: 300
      log-abandoned: true

#飞鸽微信通知
fei:
  ge:
    url: https://u.ifeige.cn/api/message/send
    secret: 9ec4e9dd4a2754039440919748a5b9d8
    app:
      key: 914cfaa74c24355a93ff0b0984baf6a0
    template:
      id: rf4ZnwD7S_NvPF9hKG2eRcqqelq-M22Nt1m8HOu-ajs
